import StatCard from '../components/StatCard'

const cards = [
  ['Total parking spots', '40', 'Across 3 zones', ''], ['Available spots', '24', '60% of capacity', 'free'], ['Occupied spots', '12', '30% of capacity', 'occupied'], ['Active sessions', '12', '3 due to exit soon', ''], ["Today's revenue", '186 DT', '+12.4% vs yesterday', 'revenue'],
]
const spots = [['A-01', 'FREE'], ['A-02', 'OCCUPIED'], ['A-03', 'RESERVED'], ['A-04', 'FREE'], ['A-05', 'MAINTENANCE'], ['B-01', 'OCCUPIED'], ['B-02', 'FREE'], ['B-03', 'FREE'], ['B-04', 'RESERVED'], ['C-01', 'FREE']]
const activity = [['↗', 'Vehicle entered', '217 TUN 894 parked in A-02', 'Just now'], ['□', 'Reservation created', 'B-04 reserved for Nour Trabelsi', '8 min ago'], ['↙', 'Vehicle exited', '198 TUN 124 left parking', '22 min ago'], ['!', 'Alert generated', 'Camera CAM-04 is offline', '31 min ago']]

export default function Dashboard() {
  return <><header className="page-head"><div><p className="eyebrow">OPERATIONS OVERVIEW</p><h1>Good morning, Balsem.</h1><p className="muted">Here is what’s happening at SmartPark Central today.</p></div><button>↻ Refresh data</button></header><section className="cards">{cards.map(([label, value, note, tone]) => <StatCard key={label} label={label} value={value} note={note} tone={tone} />)}</section><section className="dashboard-grid"><article className="panel occupancy"><div className="panel-title"><div><p className="eyebrow">LIVE CAPACITY</p><h2>Parking occupancy</h2></div><span className="live-label"><i />LIVE</span></div><div className="occupancy-body"><div className="ring"><strong>30%</strong><span>occupied</span></div><div className="occupancy-legend"><p><i className="dot free" />24 <span>Available spots</span></p><p><i className="dot occupied" />12 <span>Occupied spots</span></p><p><i className="dot reserved" />3 <span>Reserved spots</span></p><p><i className="dot maintenance" />1 <span>Maintenance</span></p></div></div><div className="duration"><span>Average parking duration</span><strong>72 min</strong><span>Peak time</span><strong>11:00 – 13:00</strong></div></article><article className="panel realtime"><div className="panel-title"><div><p className="eyebrow">SYSTEM STATUS</p><h2>Real-time status</h2></div></div><div className="connected"><span><i />Connected</span><strong>Live updates are active</strong><p>Parking events are syncing instantly.</p></div><div className="system-line"><span>API connection</span><b>Operational</b></div><div className="system-line"><span>Camera network</span><b className="warning">1 attention needed</b></div></article></section><section className="dashboard-grid lower"><article className="panel"><div className="panel-title"><div><p className="eyebrow">PARKING MAP</p><h2>Spot availability</h2></div><button className="text-button">View all spots →</button></div><div className="dashboard-spots">{spots.map(([id, status]) => <div className={`dashboard-spot ${status.toLowerCase()}`} key={id}><span>{id.startsWith('A') ? 'ZONE A' : id.startsWith('B') ? 'ZONE B' : 'ZONE C'}</span><strong>{id}</strong><small>{status}</small></div>)}</div></article><article className="panel"><div className="panel-title"><div><p className="eyebrow">ACTIVITY LOG</p><h2>Recent activity</h2></div><button className="text-button">View all →</button></div><div className="activity-list">{activity.map(([icon, title, detail, when]) => <div className="activity" key={title}><i>{icon}</i><div><strong>{title}</strong><p>{detail}</p></div><time>{when}</time></div>)}</div></article></section></>
}
