import { useState } from 'react'
import { forgotPassword, login } from '../services/api'

export default function Login({ onLogin, onRegister }) {
  const [form, setForm] = useState({ username: '', password: '' }); const [portal, setPortal] = useState('CUSTOMER'); const [error, setError] = useState(''); const [forgotOpen, setForgotOpen] = useState(false); const [forgotEmail, setForgotEmail] = useState(''); const [forgotMessage, setForgotMessage] = useState(''); const [sending, setSending] = useState(false)
  const submit = async event => { event.preventDefault(); try { const data = await login({ ...form, portal }); localStorage.setItem('smartpark_token', data.access_token); onLogin() } catch (err) { setError(err.message) } }
  const requestReset = async event => { event.preventDefault(); setSending(true); setForgotMessage(''); try { const result = await forgotPassword(forgotEmail); setForgotMessage(result.message) } catch (err) { setForgotMessage(err.message) } finally { setSending(false) } }
  return <main className="auth"><section className="auth-card"><div className="auth-brand">SP</div><p className="eyebrow">SMARTPARK AI</p><h1>Welcome back</h1><p>Choose how you want to access SmartPark.</p><div className="portal-choice"><button type="button" className={portal === 'CUSTOMER' ? '' : 'secondary'} onClick={() => setPortal('CUSTOMER')}>Customer</button><button type="button" className={portal === 'STAFF' ? '' : 'secondary'} onClick={() => setPortal('STAFF')}>Staff</button></div><p className="muted">{portal === 'STAFF' ? 'Super Admin, Admin, Operator and Security sign in here.' : 'Customers can view their parking sessions and payments here.'}</p><form onSubmit={submit}><label>Email<input required type="email" value={form.username} onChange={event => setForm({ ...form, username: event.target.value })} /></label><label>Password<input required type="password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label><button type="button" className="forgot-password" onClick={() => { setForgotOpen(true); setForgotEmail(form.username); setForgotMessage('') }}>Forgot password?</button>{error && <small className="error">{error}</small>}<button>Sign in</button></form>{forgotOpen && <div className="auth-reset"><h2>Reset your password</h2><p>Enter your email and we will send you a reset link.</p><form onSubmit={requestReset}><label>Email<input required type="email" value={forgotEmail} onChange={event => setForgotEmail(event.target.value)} /></label>{forgotMessage && <small className={forgotMessage.startsWith('If this') ? 'success' : 'error'}>{forgotMessage}</small>}<div><button type="button" className="secondary" onClick={() => setForgotOpen(false)}>Cancel</button><button disabled={sending}>{sending ? 'Sending...' : 'Send reset link'}</button></div></form></div>}{portal === 'CUSTOMER' && <p className="switch">New customer? <button type="button" onClick={onRegister}>Create an account</button></p>}</section></main>
}
