import { useMemo, useState } from 'react'

const vehicles = [
  { id: 'VH-1048', plate: '217 TUN 894', owner: 'Sami Ben Ali', phone: '+216 24 118 280', type: 'Sedan', brand: 'Toyota', model: 'Corolla', color: 'White', status: 'AUTHORIZED' },
  { id: 'VH-1047', plate: '198 TUN 124', owner: 'Nour Trabelsi', phone: '+216 55 927 401', type: 'SUV', brand: 'BMW', model: 'X3', color: 'Black', status: 'VIP' },
  { id: 'VH-1046', plate: '234 TUN 661', owner: 'Yassine Gharbi', phone: '+216 22 430 981', type: 'Hatchback', brand: 'Peugeot', model: '208', color: 'Blue', status: 'VISITOR' },
  { id: 'VH-1045', plate: '156 TUN 998', owner: 'Unknown', phone: '—', type: 'SUV', brand: 'Range Rover', model: 'Sport', color: 'Grey', status: 'BLACKLISTED' },
]
const spots = [
  ['A-01', 'A', 'Ground', 'FREE', ''], ['A-02', 'A', 'Ground', 'OCCUPIED', '217 TUN 894'], ['A-03', 'A', 'Ground', 'RESERVED', '198 TUN 124'], ['A-04', 'A', 'Ground', 'FREE', ''],
  ['A-05', 'A', 'Ground', 'MAINTENANCE', ''], ['B-01', 'B', 'Level 1', 'OCCUPIED', '234 TUN 661'], ['B-02', 'B', 'Level 1', 'FREE', ''], ['B-03', 'B', 'Level 1', 'FREE', ''],
  ['B-04', 'B', 'Level 1', 'RESERVED', '310 TUN 450'], ['C-01', 'C', 'Level 2', 'FREE', ''], ['C-02', 'C', 'Level 2', 'OCCUPIED', '111 TUN 225'], ['C-03', 'C', 'Level 2', 'FREE', ''],
]
const sessions = [
  ['PS-8241', '217 TUN 894', 'A-02', 'Today, 08:42', '—', '2h 18m', '—', 'ACTIVE'], ['PS-8240', '198 TUN 124', 'B-04', 'Today, 08:10', 'Today, 10:03', '1h 53m', '5.00 DT', 'COMPLETED'],
  ['PS-8239', '234 TUN 661', 'B-01', 'Today, 07:20', 'Today, 09:35', '2h 15m', '6.00 DT', 'COMPLETED'], ['PS-8238', '111 TUN 225', 'C-02', 'Today, 06:50', '—', '4h 10m', '—', 'ACTIVE'],
]
const reservations = [['RS-304', 'Sarra Mansour', '217 TUN 894', 'A-03', 'Today, 14:00', 'Today, 17:00', 'CONFIRMED'], ['RS-303', 'Nour Trabelsi', '198 TUN 124', 'B-04', 'Today, 16:00', 'Today, 19:00', 'PENDING'], ['RS-302', 'Mohamed Arfaoui', '310 TUN 450', 'C-01', 'Yesterday, 10:00', 'Yesterday, 12:00', 'COMPLETED']]
const users = [['US-091', 'Balsem', 'balsem@smartpark.ai', 'ADMIN', 'ACTIVE'], ['US-090', 'Nour Trabelsi', 'nour.t@smartpark.ai', 'OPERATOR', 'ACTIVE'], ['US-089', 'Fares Hadded', 'fares.h@smartpark.ai', 'SECURITY', 'ACTIVE'], ['US-088', 'Sami Ben Ali', 'sami.b@smartpark.ai', 'USER', 'INACTIVE']]
const payments = [['PY-0921', '198 TUN 124', 'PS-8240', '5.00 DT', 'Card', 'Today, 10:03', 'PAID'], ['PY-0920', '234 TUN 661', 'PS-8239', '6.00 DT', 'Cash', 'Today, 09:35', 'PAID'], ['PY-0919', '310 TUN 450', 'PS-8237', '8.00 DT', 'Mobile', 'Yesterday', 'PENDING']]
const alerts = [['AL-042', 'UNAUTHORIZED ACCESS', 'Access attempt at Gate 2 was denied.', '—', 'Today, 10:18', 'HIGH', 'OPEN'], ['AL-041', 'CAMERA OFFLINE', 'Camera CAM-04 has not responded for 8 minutes.', '—', 'Today, 09:42', 'MEDIUM', 'OPEN'], ['AL-040', 'LONG STAY', 'Vehicle has exceeded the 8-hour stay limit.', '111 TUN 225', 'Today, 08:50', 'LOW', 'OPEN']]

function Badge({ children }) { return <span className={`status ${String(children).toLowerCase().replaceAll(' ', '-')}`}>{String(children).replaceAll('_', ' ')}</span> }
function PageHead({ eyebrow, title, subtitle, action, onAction }) { return <header className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{subtitle}</p></div>{action && <button onClick={onAction}>+ {action}</button>}</header> }
function Filters({ placeholder = 'Search...', children, onSearch, onReset }) { return <div className="filters"><label className="search-field">⌕<input onChange={e => onSearch?.(e.target.value)} placeholder={placeholder} /></label>{children}{onReset && <button type="button" className="filter-button" onClick={onReset}>Reset filters</button>}</div> }
function DataTable({ columns, rows, render, empty = 'No records found.' }) { return <div className="table-wrap"><table><thead><tr>{columns.map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={row[0] || index}>{render(row, index)}</tr>) : <tr><td colSpan={columns.length} className="empty">{empty}</td></tr>}</tbody></table></div> }
function Modal({ title, fields, onClose, onSubmit }) { const [form, setForm] = useState({}); return <div className="modal-backdrop"><form className="modal" onSubmit={e => { e.preventDefault(); onSubmit(form); onClose() }}><div className="modal-title"><h2>{title}</h2><button type="button" className="plain-button" onClick={onClose}>×</button></div><div className="form-grid">{fields.map(([key, label, type = 'text', options]) => <label key={key}>{label}{type === 'select' ? <select required onChange={e => setForm({ ...form, [key]: e.target.value })}><option value="">Select {label}</option>{options.map(o => <option key={o}>{o}</option>)}</select> : <input required type={type} onChange={e => setForm({ ...form, [key]: e.target.value })} />}</label>)}</div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button>Save changes</button></div></form></div> }

export function VehiclesPage() { const [list, setList] = useState(vehicles); const [query, setQuery] = useState(''); const [modal, setModal] = useState(false); const filtered = useMemo(() => list.filter(v => `${v.plate} ${v.owner} ${v.status}`.toLowerCase().includes(query.toLowerCase())), [list, query]); return <><PageHead eyebrow="FLEET MANAGEMENT" title="Vehicles" subtitle="Manage vehicles permitted to access your parking facility." action="Add vehicle" onAction={() => setModal(true)} /><Filters placeholder="Search by plate, owner or vehicle..." onSearch={setQuery}><select><option>All statuses</option><option>AUTHORIZED</option><option>VISITOR</option><option>VIP</option><option>BLACKLISTED</option></select></Filters><DataTable columns={['ID', 'Plate number', 'Owner', 'Phone', 'Vehicle', 'Color', 'Status', 'Actions']} rows={filtered} render={v => <><td>{v.id}</td><td><strong>{v.plate}</strong></td><td>{v.owner}</td><td>{v.phone}</td><td>{v.brand} {v.model}<small>{v.type}</small></td><td><i className="color-dot" />{v.color}</td><td><Badge>{v.status}</Badge></td><td><button className="row-action">•••</button></td></>} />{modal && <Modal title="Add vehicle" onClose={() => setModal(false)} onSubmit={f => setList([{ id: `VH-${1050 + list.length}`, plate: f.plate, owner: f.owner, phone: f.phone, type: f.type, brand: f.brand, model: f.model, color: f.color, status: f.status }, ...list])} fields={[["plate", "Plate number"], ["owner", "Owner name"], ["phone", "Phone"], ["type", "Vehicle type", "select", ["Sedan", "SUV", "Hatchback"]], ["brand", "Brand"], ["model", "Model"], ["color", "Color"], ["status", "Status", "select", ["AUTHORIZED", "VISITOR", "VIP", "BLACKLISTED", "EXPIRED"]]]} />}</> }

export function SpotsPage() {
  const [list, setList] = useState(spots.map((s, i) => ({ id: i + 1, number: s[0], zone: s[1], floor: s[2], status: s[3], vehicle: s[4] })))
  const [statusFilter, setStatusFilter] = useState('ALL')
  const [zoneFilter, setZoneFilter] = useState('ALL')
  const [floorFilter, setFloorFilter] = useState('ALL')
  const shown = list.filter(s => (statusFilter === 'ALL' || s.status === statusFilter) && (zoneFilter === 'ALL' || s.zone === zoneFilter) && (floorFilter === 'ALL' || s.floor === floorFilter))
  const cycle = spot => { const states = ['FREE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE']; setList(list.map(s => s.id === spot.id ? { ...s, status: states[(states.indexOf(s.status) + 1) % states.length] } : s)) }
  const resetFilters = () => { setStatusFilter('ALL'); setZoneFilter('ALL'); setFloorFilter('ALL') }
  return <><PageHead eyebrow="FACILITY MANAGEMENT" title="Parking spots" subtitle="Monitor availability and update parking space status in real time." /><Filters onReset={resetFilters}><select aria-label="Filter by status" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="ALL">All statuses</option><option>FREE</option><option>OCCUPIED</option><option>RESERVED</option><option>MAINTENANCE</option></select><select aria-label="Filter by zone" value={zoneFilter} onChange={e => setZoneFilter(e.target.value)}><option value="ALL">All zones</option><option value="A">Zone A</option><option value="B">Zone B</option><option value="C">Zone C</option></select><select aria-label="Filter by floor" value={floorFilter} onChange={e => setFloorFilter(e.target.value)}><option value="ALL">All floors</option><option>Ground</option><option>Level 1</option><option>Level 2</option></select></Filters><div className="spot-summary">{['FREE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE'].map(x => <span key={x}><Badge>{x}</Badge> {shown.filter(s => s.status === x).length}</span>)}<span className="filtered-count">{shown.length} spot{shown.length !== 1 ? 's' : ''} shown</span></div><section className="spot-cards">{shown.map(s => <button className={`spot-card ${s.status.toLowerCase()}`} onClick={() => cycle(s)} key={s.id}><span>{s.zone} · {s.floor}</span><strong>{s.number}</strong><Badge>{s.status}</Badge>{s.vehicle && <small>⌁ {s.vehicle}</small>}</button>)}</section>{!shown.length && <div className="no-results">No parking spots match these filters.</div>}<p className="helper">Click any space to cycle its status. Connect this action to <code>PUT /parking-spots/:id/status</code> when the API is running.</p></>
}

export function SessionsPage() { const [list, setList] = useState(sessions); const exit = id => setList(list.map(s => s[0] === id ? [...s.slice(0, 4), 'Just now', '2h 18m', '7.00 DT', 'COMPLETED'] : s)); return <><PageHead eyebrow="PARKING OPERATIONS" title="Parking sessions" subtitle="Track active visits, completed sessions and vehicle exits." /><Filters placeholder="Search by plate number..."><select><option>All sessions</option><option>ACTIVE</option><option>COMPLETED</option></select></Filters><DataTable columns={['Session ID', 'Vehicle', 'Parking spot', 'Entry time', 'Exit time', 'Duration', 'Amount', 'Status', 'Actions']} rows={list} render={s => <>{s.slice(0, 7).map((x, i) => <td key={i}>{i === 1 ? <strong>{x}</strong> : x}</td>)}<td><Badge>{s[7]}</Badge></td><td>{s[7] === 'ACTIVE' ? <button className="small-button" onClick={() => exit(s[0])}>Exit vehicle</button> : <button className="row-action">•••</button>}</td></>} /></> }

export function ReservationsPage() { const [modal, setModal] = useState(false); return <><PageHead eyebrow="BOOKING MANAGEMENT" title="Reservations" subtitle="Plan parking allocations and manage upcoming vehicle arrivals." action="Create reservation" onAction={() => setModal(true)} /><Filters placeholder="Search reservation, user or plate..."><input type="date" /><select><option>All statuses</option><option>PENDING</option><option>CONFIRMED</option><option>COMPLETED</option></select></Filters><DataTable columns={['Reservation ID', 'User', 'Vehicle', 'Parking spot', 'Start time', 'End time', 'Status', 'Actions']} rows={reservations} render={r => <>{r.slice(0, 6).map((x, i) => <td key={i}>{i === 0 ? <strong>{x}</strong> : x}</td>)}<td><Badge>{r[6]}</Badge></td><td><button className="row-action">•••</button></td></>} />{modal && <Modal title="Create reservation" onClose={() => setModal(false)} onSubmit={() => {}} fields={[["user", "User"], ["vehicle", "Vehicle plate"], ["spot", "Parking spot", "select", spots.map(s => s[0])], ["start", "Start time", "datetime-local"], ["end", "End time", "datetime-local"]]} />}</> }

export function UsersPage() { const [modal, setModal] = useState(false); const [list, setList] = useState(users); return <><PageHead eyebrow="ACCESS CONTROL" title="Users" subtitle="Manage team members, operators and access permissions." action="Add user" onAction={() => setModal(true)} /><Filters placeholder="Search by name or email..."><select><option>All roles</option><option>ADMIN</option><option>OPERATOR</option><option>SECURITY</option><option>USER</option></select></Filters><DataTable columns={['User ID', 'Name', 'Email', 'Role', 'Status', 'Actions']} rows={list} render={(u, index) => <><td>{u[0]}</td><td><div className="person"><span>{u[1].slice(0, 2).toUpperCase()}</span><strong>{u[1]}</strong></div></td><td>{u[2]}</td><td><Badge>{u[3]}</Badge></td><td><Badge>{u[4]}</Badge></td><td><button className="small-button secondary" onClick={() => setList(list.map((x, i) => i === index ? [...x.slice(0, 4), x[4] === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'] : x))}>{u[4] === 'ACTIVE' ? 'Deactivate' : 'Activate'}</button></td></>} />{modal && <Modal title="Add user" onClose={() => setModal(false)} onSubmit={() => {}} fields={[["name", "Full name"], ["email", "Email", "email"], ["role", "Role", "select", ["SUPER_ADMIN", "ADMIN", "OPERATOR", "SECURITY", "USER"]], ["password", "Temporary password", "password"]]} />}</> }

export function PaymentsPage() { return <><PageHead eyebrow="FINANCIAL OVERVIEW" title="Payments" subtitle="Review completed parking transactions and outstanding balances." /><section className="mini-stats"><Metric label="Today's revenue" value="186.00 DT" note="+12.4% vs yesterday" /><Metric label="Total revenue" value="24,680.00 DT" note="All time" /><Metric label="Pending payments" value="03" note="13.00 DT awaiting payment" /><Metric label="Completed payments" value="147" note="This month" /></section><Filters placeholder="Search payment or vehicle..."><select><option>All payment statuses</option><option>PAID</option><option>PENDING</option></select></Filters><DataTable columns={['Payment ID', 'Vehicle', 'Parking session', 'Amount', 'Method', 'Date', 'Status']} rows={payments} render={p => p.map((x, i) => <td key={i}>{i === 6 ? <Badge>{x}</Badge> : i === 0 ? <strong>{x}</strong> : x}</td>)} /></> }
function Metric({ label, value, note }) { return <article><p>{label}</p><strong>{value}</strong><small>{note}</small></article> }

export function AlertsPage() { const [list, setList] = useState(alerts); return <><PageHead eyebrow="SYSTEM MONITORING" title="Alerts" subtitle="Review and resolve operational events that need attention." /><div className="alert-callout"><span>!</span><div><strong>2 alerts require immediate attention</strong><p>Stay ahead of issues before they impact drivers and operations.</p></div><button className="secondary">View critical</button></div><Filters placeholder="Search alerts..."><select><option>All severity</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></Filters><DataTable columns={['Alert ID', 'Type', 'Description', 'Vehicle', 'Date/time', 'Severity', 'Status', 'Actions']} rows={list} render={(a, index) => <>{a.slice(0, 5).map((x, i) => <td key={i}>{i === 0 ? <strong>{x}</strong> : x}</td>)}<td><Badge>{a[5]}</Badge></td><td><Badge>{a[6]}</Badge></td><td>{a[6] === 'OPEN' && <button className="small-button" onClick={() => setList(list.map((x, i) => i === index ? [...x.slice(0, 6), 'RESOLVED'] : x))}>Resolve</button>}</td></>} /></> }

export function AnalyticsPage() { const days = [42, 56, 48, 70, 64, 84, 73]; const hours = [22, 35, 58, 82, 65, 46, 30]; return <><PageHead eyebrow="PERFORMANCE INSIGHTS" title="Analytics" subtitle="Understand demand, occupancy and revenue patterns across your facility." /><div className="analytics-grid"><Chart title="Parking occupancy" caption="Occupancy rate over the last 7 days" values={days} /><Chart title="Daily revenue" caption="Revenue performance in TND" values={[38, 52, 40, 67, 58, 86, 73]} currency /><article className="panel chart-panel"><p className="eyebrow">PEAK ACTIVITY</p><h2>Peak parking hours</h2><div className="hour-bars">{hours.map((v, i) => <div key={i}><i style={{ height: `${v}%` }} /><small>{8 + i}:00</small></div>)}</div></article><article className="insight-panel"><p className="eyebrow">KEY METRICS</p><h2>Today at a glance</h2><div><span>Average parking duration</span><strong>72 min</strong></div><div><span>Occupancy rate</span><strong>40%</strong></div><div><span>Vehicles today</span><strong>52</strong></div><div><span>Peak entry time</span><strong>11:00</strong></div></article></div></> }
function Chart({ title, caption, values, currency }) { const points = values.map((v, i) => `${(i / (values.length - 1)) * 100},${100 - v}`).join(' '); return <article className="panel chart-panel"><p className="eyebrow">{currency ? 'REVENUE' : 'CAPACITY'}</p><h2>{title}</h2><p className="muted">{caption}</p><svg viewBox="0 0 100 110" preserveAspectRatio="none"><line x1="0" y1="25" x2="100" y2="25" /><line x1="0" y1="55" x2="100" y2="55" /><line x1="0" y1="85" x2="100" y2="85" /><polyline points={points} /></svg><div className="chart-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></article> }

export function SettingsPage() { return <><PageHead eyebrow="PLATFORM CONFIGURATION" title="Settings" subtitle="Configure your parking facility, notifications and account preferences." /><div className="settings-layout"><section className="settings-nav"><button className="active">General</button><button>Facility</button><button>Notifications</button><button>Security</button><button>Integrations</button></section><section className="panel settings-panel"><h2>General settings</h2><p className="muted">Update basic information for your SmartPark workspace.</p><div className="form-grid"><label>Facility name<input defaultValue="SmartPark Central" /></label><label>Timezone<select defaultValue="Africa/Tunis"><option>Africa/Tunis</option><option>Europe/Paris</option></select></label><label>Support email<input defaultValue="support@smartpark.ai" /></label><label>Currency<select defaultValue="TND"><option>TND — Tunisian Dinar</option><option>EUR — Euro</option></select></label></div><hr /><div className="toggle-row"><div><strong>Live dashboard updates</strong><p>Receive parking status updates instantly.</p></div><button className="toggle on" aria-label="Live updates enabled"><i /></button></div><div className="toggle-row"><div><strong>Daily operations report</strong><p>Receive a summary by email every morning.</p></div><button className="toggle" aria-label="Daily report disabled"><i /></button></div><button>Save settings</button></section></div></> }
